force-app/main/default/objects/GarbageCollector__mdt/GarbageCollector__mdt.object-meta.xml
<CustomObject>
    <label>Garbage Collector</label>
    <pluralLabel>Garbage Collectors</pluralLabel>
</CustomObject>

force-app/main/default/objects/GarbageCollector__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Indicates whether the current garbage collector is active or not.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GarbageCollector__mdt/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <inlineHelpText>The fully qualified name of an Apex Class which contains custom logic for querying records to be deleted. This apex class must implement the GarbageCollector.QueryLocator interface.</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GarbageCollector__mdt/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <defaultValue>200</defaultValue>
    <inlineHelpText
	>The maximum number of records that can be deleted in a single batch. All records will be processed in an asynchronous context.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GarbageCollector__mdt/fields/HardDelete__c.field-meta.xml
<CustomField>
    <fullName>HardDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText
	>When checked, records deleted by the garbage collector will skip the recycle bin, permanently deleting them right away.</inlineHelpText>
    <label>Hard Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GarbageCollector__mdt/fields/QueryWhereClause__c.field-meta.xml
<CustomField>
    <fullName>QueryWhereClause__c</fullName>
    <defaultValue>&quot;LastModifiedDate &lt; LAST_N_DAYS:30&quot;</defaultValue>
    <inlineHelpText>The WHERE Clause of a SOQL Query that defines which records should be deleted, in a &quot;Query Based&quot; Garbage Collector.

This result will be injected into the &quot;WHERE&quot; clause, as demonstrated below:

SELECT Id
FROM MyObject__c
WHERE {{QueryWhereClause__c}}</inlineHelpText>
    <label>Query Where Clause</label>
    <length>19000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GarbageCollector__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <inlineHelpText>The API Name of a Salesforce Object to be deleted. Examples of valid values include:

- &quot;Account&quot;
- &quot;My_Custom_Object__c&quot;
- &quot;namespace__My_Packaged_Object__c&quot;</inlineHelpText>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Garbage Collectors</relationshipLabel>
    <relationshipName>GarbageCollectors</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/GarbageCollector__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Query Based&quot;</defaultValue>
    <inlineHelpText>Indicates how the garbage collector will retrieve records to be deleted:

- Apex Based: Use an apex class that implements the &quot;GarbageCollector.Worker&quot; interface to define custom query logic. Choose this option when a simple SOQL query is not enough to capture your requirements.

- Query Based: A SOQL query is built using the provided &quot;SObjectType&quot; and &quot;Query Where Clause&quot;. This option should cover most garbage collection use cases.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex Based</fullName>
                <default>true</default>
                <label>Apex Based</label>
            </value>
            <value>
                <fullName>Query Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GarbageCollectorMetadataSelector.cls
public without sharing abstract class GarbageCollectorMetadataSelector {
	@TestVisible
	private static Map<String, GarbageCollector__mdt> settings;

	public static Map<String, GarbageCollector__mdt> getAll() {
        // Retrieve all garbage collector records, mapped by their Developer Names
        GarbageCollectorMetadataSelector.init();
		return settings;
	}

    public static GarbageCollector__mdt get(String developerName) {
        // Retrieve a single Garbage Collector record by its Developer Name
        GarbageCollectorMetadataSelector.init();
        return settings?.get(developerName);
    }

    // **** PRIVATE **** //
    @TestVisible
    private static void init() {
        // Lazily-initialization; query & Map metadata if it hasn't already been done this transaction
        settings = settings ?? GarbageCollectorMetadataSelector.retrieveFromDatabase();
    }

    @TestVisible
    static Map<String, GarbageCollector__mdt> mapByDeveloperName(List<GarbageCollector__mdt> records) {
        // Map the provided list of metadata records by their developer name
        Map<String, GarbageCollector__mdt> recordMap = new Map<String, GarbageCollector__mdt>();
        for (GarbageCollector__mdt record : records) {
			String developerName = record?.DeveloperName;
			recordMap?.put(developerName, record);
		}
		return recordMap;
    }

    static List<GarbageCollector__mdt> queryRecords() {
        // Retrieve all garbage collector records in the org via SOQL
        // * Note: Normally, we'd use GarbageCollector__mdt.getAll() to save a SOQL query
        // * However, that method does not support relationship fields (ie., SObjectType__r.QualifiedApiName)
        // * or long text area fields (ie., QueryWhereClause__c)
        return [
			SELECT
				Id,
				Active__c,
				ApexClassName__c,
				BatchSize__c,
				DeveloperName,
				HardDelete__c,
				QueryWhereClause__c,
				SObjectType__r.QualifiedApiName,
				Type__c
			FROM GarbageCollector__mdt
            WITH SYSTEM_MODE
		];
    }

    private static Map<String, GarbageCollector__mdt> retrieveFromDatabase() {
        // Query for any Garbage Collector records, and map them by their Developer Names
		List<GarbageCollector__mdt> records = GarbageCollectorMetadataSelector.queryRecords();
        return GarbageCollectorMetadataSelector.mapByDeveloperName(records);
	}
}