force-app/main/default/objects/GarbageCollectorSettings__c/GarbageCollectorSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Optional global settings which govern the Garbage Collector application.</description>
    <label>Garbage Collector Settings</label>
</CustomObject>

force-app/main/default/objects/GarbageCollectorSettings__c/fields/LogAdapter__c.field-meta.xml
<CustomField>
    <fullName>LogAdapter__c</fullName>
    <inlineHelpText>The fully qualified API name (including namespace, if applicable) of the apex class used by the Garbage Collector framework for logging purposes. This apex class must have a public 0-argument constructor, and must implement the GarbageCollectorLogs.Adapter interface. 

This interface has two required methods:
- void log(System.LoggingLevel level, Object message);
- void save();

When left blank, or when no settings are defined, the application will print to traditional debug logs by default.</inlineHelpText>
    <label>Log Adapter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GarbageCollectorLogsTest.cls
@IsTest 
public class GarbageCollectorLogsTest {
    // **** CONSTANTS **** //
    private static final Type DEFAULT_ADAPTER_TYPE = GarbageCollectorLogs.DefaultLogger.class;

    // **** TESTS **** //
    @IsTest 
    static void shouldUseProvidedAdapter() {
        Type adapterType = GarbageCollectorLogsTest.TestAdapter.class;
        GarbageCollectorSettings__c settings = new GarbageCollectorSettings__c(
            LogAdapter__c = adapterType?.getName(),
            Name = 'Test'
        ); 
        insert settings;


        Test.startTest();
        GarbageCollectorLogs.Adapter adapter = GarbageCollectorLogs.init();
        Test.stopTest();

        Assert.areNotEqual(null, adapter, 'Returned null GarbageCollectorLogs.Adapter');
        Assert.isInstanceOfType(adapter, adapterType, 'Wrong type of GarbageCollectorLogs.Adapter');
    }

    @IsTest 
    static void shouldUseDefaultLoggerIfSpecified() {
        GarbageCollectorSettings__c settings = new GarbageCollectorSettings__c(
            LogAdapter__c = DEFAULT_ADAPTER_TYPE?.getName(),
            Name = 'Test'
        ); 
        insert settings;

        Test.startTest();
        GarbageCollectorLogs.Adapter adapter = GarbageCollectorLogs.init();
        Test.stopTest();

        Assert.areNotEqual(null, adapter, 'Returned null GarbageCollectorLogs.Adapter');
        Assert.isInstanceOfType(adapter, DEFAULT_ADAPTER_TYPE, 'Wrong type of GarbageCollectorLogs.Adapter');
    }

    @IsTest 
    static void shouldUseDefaultLoggerIfNoSettingsDefined() {
        Test.startTest();
        GarbageCollectorLogs.Adapter adapter = GarbageCollectorLogs.init();
        Test.stopTest();

        Assert.areNotEqual(null, adapter, 'Returned null GarbageCollectorLogs.Adapter');
        Assert.isInstanceOfType(adapter, DEFAULT_ADAPTER_TYPE, 'Wrong type of GarbageCollectorLogs.Adapter');
    }

    @IsTest 
    static void shouldUseDefaultLoggerIfNoLogAdapterDefined() {
        GarbageCollectorSettings__c settings = new GarbageCollectorSettings__c(Name = 'Test');
        insert settings;

        Test.startTest();
        GarbageCollectorLogs.Adapter adapter = GarbageCollectorLogs.init();
        Test.stopTest();

        Assert.areNotEqual(null, adapter, 'Returned null GarbageCollectorLogs.Adapter');
        Assert.isInstanceOfType(adapter, DEFAULT_ADAPTER_TYPE, 'Wrong type of GarbageCollectorLogs.Adapter');
    }

    @IsTest 
    static void shouldUseDefaultLoggerIfInvalidLogAdapter() {
        GarbageCollectorSettings__c settings = new GarbageCollectorSettings__c(
            LogAdapter__c = 'abcd1234', // Not a real log adapter!
            Name = 'Test'
        );
        insert settings;

        Test.startTest();
        GarbageCollectorLogs.Adapter adapter = GarbageCollectorLogs.init();
        Test.stopTest();

        Assert.areNotEqual(null, adapter, 'Returned null GarbageCollectorLogs.Adapter');
        Assert.isInstanceOfType(adapter, DEFAULT_ADAPTER_TYPE, 'Wrong type of GarbageCollectorLogs.Adapter');
    }

    @IsTest 
    static void shouldUseDefaultLoggingBehavior() {
        // This method is mostly for coverage, since we can't check/assert standard System.debug behavior
        GarbageCollectorLogs.Adapter logger = new GarbageCollectorLogs.DefaultLogger();

        Test.startTest();
        try {
            logger?.log(System.LoggingLevel.INFO, 'This is a test!');
            logger?.save();
        } catch (Exception error) {
            Assert.fail('Failed to log: ' + error); 
        }
        Test.stopTest();
    }

    // **** SETUP **** // 
    @TestSetup 
    static void setup() {
        delete [SELECT Id FROM GarbageCollectorSettings__c];
    }

    // **** INNER **** // 
    @SuppressWarnings('PMD.EmptyStatementBlock')
    public class TestAdapter implements GarbageCollectorLogs.Adapter {
        public void log(System.LoggingLevel level, Object message) {
            // This test adapter doesn't need to do anything
        }

        public void save() {
            // This test adapter doesn't need to do anything
        }
    }
}